apiVersion: v1
kind: Secret
metadata:
  name: unifiapay-secrets
  namespace: unifiapay
type: Opaque
stringData:
  pix-key: "unifiap-pix-555354-key-simulation"
  db-password: "secure-password-555354"
  api-token: "unifiap-token-555354"
