apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifiapay-logs-pvc
  namespace: unifiapay
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifiapay-data-pvc
  namespace: unifiapay
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
